apiVersion: v1
kind: Service
metadata:
  name: java_app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: java_app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java_app
  template:
    metadata:
      labels:
        app: java_app
    spec:
      containers:
      - name: java_app
        image: mhali/java_app:latest
        ports:
        - containerPort: 8080
